'use strict';
const ingredients = [ ['米线','主食'], ['干木耳','泡发'], ['韭菜','切短段'], ['干香菇','留泡发水'], ['小青菜','洗净'], ['番茄','切片'], ['鲜肉末','煮熟'], ['葱末','最后撒'], ['干腐竹','泡软'], ['豆芽','洗净'] ];
const chapters = ['食材准备','备菜时间','处理米线','煮一锅鲜汤','上桌开饭'];
const steps = [
  {title:'先把食材，准备齐。',short:'食材清单',chapter:0,image:'ingredients',alt:'橘色小猫坐在木桌后，面前摆着米线、木耳、韭菜、香菇、青菜、番茄、肉末、葱末、腐竹和豆芽。'},
  {title:'给肉末一点底味',short:'拌好肉末',chapter:1,image:'prep-00',supplement:true,how:'鲜肉末放入碗中，按口味加入少量盐、生抽或胡椒粉，轻轻拌匀。暂时不用的肉末放回冰箱冷藏。',why:'先把调味拌开，让肉末下锅后有底味；口味清淡也可以只在汤里调味。',tip:'盐先少放，最后尝汤时再调整。生抽、胡椒粉是可选建议。'},
  {title:'把韭菜切成短段',short:'切韭菜',chapter:1,image:'prep-01',how:'韭菜择去老叶，洗净、沥水后切成短段，放在小碗里备用。',why:'短段容易夹取，也能均匀散在汤里。韭菜留到后段下锅，香味更明显。',tip:'切好的韭菜先放一旁，不要和葱末混在一起。'},
  {title:'让木耳慢慢泡开',short:'泡木耳',chapter:1,image:'prep-02',how:'干木耳放进干净的碗，加入清水，按包装说明泡发。完全舒展后洗净，去掉根部较硬的部分。',why:'泡发让干木耳恢复柔软，洗净后更容易切，也更容易在汤中煮熟。',tip:'泡发可提前开始。泡好后及时烹饪，避免长时间室温浸泡。'},
  {title:'把木耳切成细丝',short:'切木耳',chapter:1,image:'prep-03',how:'泡好的木耳沥去水分，放在案板上切成细丝，装碗备用。',why:'细丝受热更均匀，能和米线一起夹起，每一口都有脆嫩的口感。',tip:'木耳较滑，沥水后再切，扶食材的手与刀刃保持距离。'},
  {title:'泡香菇，留下鲜味',short:'泡香菇',chapter:1,image:'prep-04',how:'干香菇先冲洗，再放进干净的清水里，按包装说明泡软。捞出香菇，把干净的泡发水留在小碗中。',why:'香菇泡软后方便切丝，干净的泡发水可以给番茄汤增加菌菇香气。',tip:'泡发水若有泥沙就过滤，底部沉淀不要倒入；有异味时弃用，改用清水。'},
  {title:'香菇切丝，汤水备用',short:'切香菇',chapter:1,image:'prep-05',how:'泡软的香菇去掉较硬的菇柄，切成细丝。盛香菇水的小碗放在旁边，等煮汤时再用。',why:'切细后香菇更容易和木耳一起炒香，也方便汤汁的鲜味散开。',tip:'把香菇丝和香菇水分开放，后面会分两次入锅。'},
  {title:'切开一颗酸甜番茄',short:'切番茄',chapter:1,image:'prep-06',how:'番茄洗净去蒂，放在案板上切成薄片，连同切出的汁水一起留好。',why:'薄片炒软更快，番茄的汁水就是这一锅汤的酸甜底味。',tip:'喜欢汤更浓，可以把番茄片再切小一些。'},
  {title:'把小青菜洗净切好',short:'切青菜',chapter:1,image:'prep-07',how:'小青菜掰开洗净，尤其洗净根部夹着的泥沙。沥水后切成细条，较厚的菜梗可以再切细一点。',why:'大小接近的菜条熟得更均匀，也能更好地与米线搭配。',tip:'青菜不用太早入锅，等汤底煮好后再加。'},
  {title:'腐竹泡软，再切小段',short:'处理腐竹',chapter:1,image:'prep-08',how:'干腐竹按包装说明用清水泡软，确认中间没有硬芯，再切成方便入口的短段。',why:'充分泡软后，腐竹才能均匀吸进汤汁，吃起来柔软又有豆香。',tip:'木耳、香菇、腐竹可以分碗同时泡发，泡发时间以各自包装为准。'},
  {title:'先把米线煮到合适',short:'煮米线',chapter:2,image:'prep-09',how:'锅中烧开足量清水，放入米线，轻轻拨散。按米线包装要求煮熟后捞出。',why:'米线先单独煮好，后面放进汤底时只需重新热透，汤也更清爽。',tip:'干米线与鲜米线做法不同，是否预泡、煮多久，以包装说明为准。'},
  {title:'过一遍凉水，沥干',short:'米线过凉水',chapter:2,image:'prep-10',how:'煮好的米线放进滤篮，用干净的可饮用凉水冲散，沥去多余水分，准备回锅。',why:'过凉水可以冲掉部分表面淀粉，让米线更松散，减少粘连。',tip:'米线暂时放一旁，后面还要进热汤重新煮透、热透。'},
  {title:'先炒出菌菇的香',short:'炒木耳香菇',chapter:3,image:'prep-11',supplement:true,how:'锅中加入少量食用油，中火加热，放入沥干的木耳丝和香菇丝翻炒，炒出香气。',why:'先炒菌菇，让油带出香气，为番茄汤打一个鲜香的底。',tip:'木耳表面有水时容易溅油，沥干后再下锅。'},
  {title:'把番茄炒软、炒出汁',short:'加入番茄',chapter:3,image:'prep-12',supplement:true,how:'加入番茄片，和木耳、香菇一起翻炒，直到番茄变软、慢慢出汁。',why:'把番茄的酸甜炒进汤底，之后加水，汤色和滋味才更均匀。',tip:'如果锅里太干，补少量清水，避免粘底。'},
  {title:'加水，煮成一锅汤',short:'加入香菇水',chapter:3,image:'prep-13',supplement:true,how:'倒入干净、过滤后的香菇水，再补清水到足够盛汤的量。把番茄和菌菇汤煮开。',why:'把香菇的鲜和番茄的酸甜融在一起，这就是米线的汤底。',tip:'水量按吃饭人数与喜欢的汤量调整。图片里的提前出现的米线仅作示意，米线在后面加入。'},
  {title:'放入肉末，拨散煮熟',short:'煮熟肉末',chapter:3,image:'prep-14',supplement:true,how:'汤煮开后，加入准备好的肉末，用筷子或勺子轻轻拨散，继续加热，确保肉末完全熟透。',why:'拨散后不会结成大团，每一口米线都能带上一点肉香。',tip:'这一步按图片采用汤中煮肉末的做法；先把肉末煮透，再进行后续步骤。'},
  {title:'给热汤加一点爽脆',short:'加入豆芽',chapter:3,image:'prep-15',supplement:true,how:'豆芽挑去不新鲜的部分，洗净、沥水后放入汤中，翻匀并继续煮熟。',why:'豆芽为汤增加清甜，也让柔软的米线多一层爽脆口感。',tip:'豆芽需要煮熟，翻动一下，让它们都浸入热汤。'},
  {title:'腐竹和青菜，一起下锅',short:'放腐竹青菜',chapter:3,image:'prep-17',supplement:true,how:'放入已泡软的腐竹段和青菜条，轻轻翻动。煮到腐竹热透、菜梗熟软，再加入备好的韭菜短段。',why:'腐竹吸收汤汁，青菜和韭菜带来清香；后放韭菜，口感与香气更好。',tip:'韭菜在这里入锅。配图展示腐竹和青菜，韭菜的加入以这段说明为准。'},
  {title:'让米线回到热汤里',short:'米线回锅',chapter:3,image:'prep-18',supplement:true,how:'将沥干的米线放入汤锅，轻轻拨散，与肉末、蔬菜拌匀，继续加热至汤重新煮开、米线热透。',why:'让米线裹上番茄菌菇汤，也把之前过凉水的米线重新加热。',tip:'米线已经煮熟，回锅后热透即可，避免反复久煮变软烂。'},
  {title:'尝一小口，调成喜欢的味道',short:'尝汤调味',chapter:3,image:'prep-19',supplement:true,how:'先确认肉末、豆芽和蔬菜都已煮熟。用干净小勺舀一点汤，稍放凉再尝，按口味少量补盐或生抽。',why:'最后再调味，可以把肉末里的底味也算进去，避免汤太咸。',tip:'调味少量多次；添加调味后搅匀，再尝一次。'},
  {title:'盛起米线，也盛满配菜',short:'盛入碗中',chapter:4,image:'finished',reference:true,how:'先把米线盛进陶瓷碗，放上肉末、木耳、香菇、腐竹和蔬菜，最后舀入热乎乎的番茄汤。',why:'先放米线再放配菜，碗里层次更清楚，也方便每个人分到丰富的食材。',tip:'汤不要盛得太满，给端碗留一点余地。'},
  {title:'最后，撒一小把葱花',short:'撒葱花',chapter:4,image:'finished',how:'在盛好的米线上撒少量葱末，让热汤轻轻烘出葱香。',why:'葱花最后放，颜色好看，香气也更清新。',tip:'葱末按自己的喜好添加，喜欢清淡就少放一点。'},
  {title:'把这一碗热乎，端上桌',short:'端上桌',chapter:4,image:'finished',reference:true,how:'用隔热垫或托盘端起汤碗，轻轻放到餐桌中央。准备好筷子和汤匙，叫朋友一起来吃。',why:'米线刚出锅时口感最好，这碗酸甜鲜香的家常味，趁热分享。',tip:'碗和汤都很烫，稳稳端好，入口前先稍稍放凉。'}
];
// The ingredient overview is not counted as a cooking step.
const total=steps.length-1;
const state={index:0,checked:new Set(),done:new Set()};
const $=id=>document.getElementById(id);
const asset=s=>`assets/${s.image}.jpg`;
const number=n=>String(n).padStart(2,'0');
let toastTimeout;
function toast(message){$('toast').textContent=message;$('toast').classList.add('show');clearTimeout(toastTimeout);toastTimeout=setTimeout(()=>$('toast').classList.remove('show'),2400)}
function checklist(prefix){return ingredients.map(([name,note],i)=>`<label class="ingredient" for="${prefix}-${i}"><input id="${prefix}-${i}" type="checkbox" data-ingredient="${i}" ${state.checked.has(i)?'checked':''}><span>${name}</span><small>${note}</small></label>`).join('')}
function updateChecks(){document.querySelectorAll('[data-ingredient]').forEach(input=>{input.checked=state.checked.has(Number(input.dataset.ingredient))});const count=$('ingredient-count');if(count)count.textContent=`已备好 ${state.checked.size} / ${ingredients.length} 样`;const all=$('check-all');if(all)all.textContent=state.checked.size===ingredients.length?'取消全选':'全部备齐';}
function renderProgress(){ $('completion-text').textContent=`已完成 ${state.done.size} / ${total} 步`;$('progress').setAttribute('aria-valuemax',String(total));$('progress').setAttribute('aria-valuenow',String(state.done.size));$('progress-fill').style.width=`${state.done.size/total*100}%`;document.querySelectorAll('.film').forEach(el=>{const n=Number(el.dataset.step);el.classList.toggle('active',n===state.index);el.classList.toggle('done',state.done.has(n));el.setAttribute('aria-current',n===state.index?'step':'false');el.setAttribute('aria-label',`${n===0?'食材清单':`第${n}步 ${steps[n].short}`}${state.done.has(n)?'，已完成':''}`)});}
function render(){const s=steps[state.index];$('step-photo').src=asset(s);$('step-photo').alt=s.alt||`小猫制作米线的图解：${s.short}${s.reference?'，使用成品参考图':''}`;$('photo-open').setAttribute('aria-label',`放大图片：${s.short}`);$('photo-caption').textContent=s.reference?'成品参考 · 本步做法见右侧说明':'小猫陪你下厨';$('step-label').innerHTML=state.index===0?'开始之前 · 食材清单':`STEP ${number(state.index)} / ${total}${s.supplement?'<span class="supplement">补充建议</span>':''}`;
 $('chapters').innerHTML=chapters.map((name,c)=>`<button type="button" class="chapter ${c===s.chapter?'active':''}" data-chapter="${c}" ${c===s.chapter?'aria-current="step"':''}><b>${number(c+1)}</b>${name}</button>`).join('');
 if(state.index===0){$('step-content').innerHTML=`<h2>${s.title}</h2><p class="step-lead">十样家常食材，就是这一碗的全部心意。<br>边准备边勾选，准备好了就和小猫开工。</p><div class="checklist">${checklist('main')}</div><div class="checklist-status"><span id="ingredient-count">已备好 ${state.checked.size} / 10 样</span><button type="button" id="check-all">${state.checked.size===10?'取消全选':'全部备齐'}</button></div><p class="seasoning-note"><strong>另备基础调味</strong> 食用油、盐，生抽与胡椒粉可选。<br>用量按人数和口味自定，调味为补充建议。</p>`;$('step-controls').innerHTML='<span class="quiet">不着急，我们一步一步来。</span><button type="button" class="primary" id="start-cooking">开始做米线</button>';
 }else{$('step-content').innerHTML=`<h2>${s.title}</h2><p class="step-lead">${chapters[s.chapter]} · ${s.short}</p><div class="step-body"><div class="explanation"><h3>这一步怎么做</h3><p>${s.how}</p></div><div class="explanation purpose"><h3>为什么这样做</h3><p>${s.why}</p></div><p class="tip"><b>小提醒</b>${s.tip}</p>${state.done.has(state.index)?'<p class="step-done">✓ 这一步已经完成了 <button type="button" class="small-link" id="undo-step">撤销勾选</button></p>':''}</div>`;$('step-controls').innerHTML=`<button type="button" class="secondary" id="previous">上一步</button><div class="control-right">${state.index<total?'<button type="button" class="quiet" id="next">先看下一步</button>':''}<button type="button" class="primary" id="complete-step">${state.index===total?'端上桌，开饭啦':state.done.has(state.index)?'继续下一步':'完成这步，继续'}</button></div>`;}
 $('step-content').getAnimations().forEach(a=>a.cancel());if(!matchMedia('(prefers-reduced-motion: reduce)').matches)$('step-content').animate([{opacity:.5,transform:'translateY(5px)'},{opacity:1,transform:'translateY(0)'}],{duration:220});renderProgress();const next=steps[state.index+1];if(next){const img=new Image();img.src=asset(next)}
}
function goToStep(index,{scroll=false}={}){if(!Number.isInteger(index)||index<0||index>total)throw new Error('步骤编号必须在 0 到 '+total+' 之间');state.index=index;render();const film=$('filmstrip').querySelector(`[data-step="${index}"]`);if(film){const box=$('filmstrip');box.scrollTo({left:film.offsetLeft-box.offsetLeft-box.clientWidth/2+film.clientWidth/2,behavior:'smooth'})}if(scroll)$('chapters').scrollIntoView({behavior:'smooth',block:'start'});}
function completeStep(){if(state.index===0)return;state.done.add(state.index);if(state.index===total){render();$('finish-copy').textContent=state.done.size===total?`${total} 个小步骤，变成了一碗热乎乎的米线。叫上朋友，趁热吃吧。`:`米线可以上桌啦。你勾选完成了 ${state.done.size} / ${total} 步，也可以回看尚未勾选的步骤。`;$('finish-dialog').showModal();return}goToStep(state.index+1);}
function openIngredients(){$('dialog-checklist').innerHTML=checklist('dialog');$('ingredients-dialog').showModal()}
function openSteps(){$('step-list').innerHTML=chapters.map((name,c)=>`<section class="directory-group"><h3>${number(c+1)} ${name}</h3>${steps.map((s,n)=>s.chapter===c?`<button type="button" class="directory-step ${state.index===n?'active':''}" data-jump="${n}"><span>${n===0?'·':number(n)}</span><span>${s.short}</span><span>${state.done.has(n)?'已完成':'查看'}</span></button>`:'').join('')}</section>`).join('');$('steps-dialog').showModal()}
$('filmstrip').innerHTML=steps.map((s,n)=>`<button type="button" class="film ${n===0?'active':''}" data-step="${n}"><img src="${asset(s)}" alt="" width="96" height="102" loading="lazy"><span><b>${n===0?'·':number(n)}</b>${s.short}</span></button>`).join('');
document.addEventListener('change',event=>{const input=event.target.closest('[data-ingredient]');if(!input)return;const n=Number(input.dataset.ingredient);input.checked?state.checked.add(n):state.checked.delete(n);updateChecks()});
document.addEventListener('click',event=>{const button=event.target.closest('button');if(!button)return;const id=button.id;if(button.hasAttribute('data-close')){button.closest('dialog').close();return}if(button.dataset.chapter!==undefined){goToStep(steps.findIndex(s=>s.chapter===Number(button.dataset.chapter)));return}if(button.dataset.step!==undefined){goToStep(Number(button.dataset.step),{scroll:true});return}if(button.dataset.jump!==undefined){$('steps-dialog').close();goToStep(Number(button.dataset.jump),{scroll:true});return}switch(id){case 'ingredients-open':openIngredients();break;case 'steps-open':case 'step-directory':openSteps();break;case 'start-cooking':goToStep(1);break;case 'previous':goToStep(state.index-1);break;case 'next':goToStep(state.index+1);break;case 'complete-step':completeStep();break;case 'check-all':if(state.checked.size===ingredients.length)state.checked.clear();else ingredients.forEach((_,i)=>state.checked.add(i));updateChecks();break;case 'undo-step':state.done.delete(state.index);render();break;case 'photo-open':$('large-photo').src=asset(steps[state.index]);$('large-photo').alt=$('step-photo').alt;$('large-caption').textContent=steps[state.index].reference?'成品参考图 · '+steps[state.index].short:steps[state.index].short;$('photo-dialog').showModal();break;}});
document.querySelector('.brand').addEventListener('click',event=>{event.preventDefault();goToStep(0,{scroll:true})});
document.querySelectorAll('dialog').forEach(dialog=>dialog.addEventListener('click',event=>{if(event.target===dialog){const r=dialog.getBoundingClientRect();if(event.clientX<r.left||event.clientX>r.right||event.clientY<r.top||event.clientY>r.bottom)dialog.close()}}));
render();
// Expose the same reading, navigation and completion actions to supporting browsers.
if(document.modelContext?.registerTool){
 const lifecycle=new AbortController();
 const definitions=[
  {name:'read_recipe_progress',title:'查看米线教程进度',description:'读取当前步骤、食材勾选和已完成的步骤，不更改页面。',inputSchema:{type:'object',properties:{},additionalProperties:false},annotations:{readOnlyHint:true},execute(){return {step:state.index,title:steps[state.index].title,total,preparedIngredients:[...state.checked].map(i=>ingredients[i][0]),completedSteps:[...state.done].sort((a,b)=>a-b)}}},
  {name:'navigate_recipe_step',title:'查看米线步骤',description:'跳转到指定步骤，0 是食材清单；仅浏览，不会标记完成。',inputSchema:{type:'object',properties:{step:{type:'integer',minimum:0,maximum:total}},required:['step'],additionalProperties:false},annotations:{readOnlyHint:false},execute(input){if(!input||Object.keys(input).some(k=>k!=='step'))throw new Error('请只提供 step');goToStep(input.step);return {step:state.index,title:steps[state.index].title,how:steps[state.index].how||'准备并勾选十种食材',purpose:steps[state.index].why||'确认食材齐备'}}},
  {name:'mark_recipe_steps_complete',title:'勾选做好的米线步骤',description:'只把用户实际已完成的步骤勾选完成；不会替用户烹饪。支持一次勾选多步。',inputSchema:{type:'object',properties:{steps:{type:'array',items:{type:'integer',minimum:1,maximum:total},minItems:1,uniqueItems:true}},required:['steps'],additionalProperties:false},annotations:{readOnlyHint:false},execute(input){if(!input||Object.keys(input).some(k=>k!=='steps')||!Array.isArray(input.steps)||!input.steps.length||input.steps.some(n=>!Number.isInteger(n)||n<1||n>total))throw new Error('请提供有效的烹饪步骤编号');input.steps.forEach(n=>state.done.add(n));render();return {completedSteps:[...state.done].sort((a,b)=>a-b),total}}}
 ];
 for(const definition of definitions){try{Promise.resolve(document.modelContext.registerTool(definition,{signal:lifecycle.signal})).catch(()=>{})}catch{}}
 window.addEventListener('pagehide',()=>lifecycle.abort(),{once:true});
}
